apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: app-test
spec:
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic.git
      ref:
        branch: main